annotation_span_categories:
- name: Appeal_to_Authority
  description: "\n    Stating that a claim is true simply because a valid authority\
    \ or expert on the issue said it was true, without any other supporting evidence\
    \ offered. We consider the special case in which the reference is not an authority\
    \ or an expert in this technique, altough it is referred to as Testimonial in\
    \ literature.\n    Example 1: \"Richard Dawkins, an evolutionary biologist and\
    \ perhaps the foremost expert in the field, says that evolution is true. Therefore,\
    \ it's true.\"\n    Explanation: Richard Dawkins certainly knows about evolution,\
    \ and he can confidently tell us that it is true, but that doesn't make it true.\
    \ What makes it true is the preponderance of evidence for the theory.\n    Example\
    \ 2: \"According to Serena Williams, our foreign policy is the best on Earth.\
    \ So we are in the right direction.\" Details: since there is a chance that any\
    \ authority can be wrong, it is reasonable to defer to an authority to support\
    \ a claim, but the authority should not be the only justification to accept the\
    \ claim, otherwise the Appeal-to-Authority fallacy is committed.\n    "
- name: Appeal_to_fear-prejudice
  description: "\n    Seeking to build support for an idea by instilling anxiety and/or\
    \ panic in the population towards an alternative.\n    In some cases the support\
    \ is built based on preconceived judgements.\n    Example 1: \"either we go to\
    \ war or we will perish\" (this is also aBlack and White fallacy))\n    Example\
    \ 2: \"we must stop those refugees as they are terrorists\"\n    "
- name: Bandwagon
  description: "\n    Attempting to persuade the target audience to join in and take\
    \ the course of action because \"everyone else is taking the same action\".\n\
    \    Example 1: \"Would you vote for Clinton as president? 57% say yes\"\n   \
    \ Example 2: \"90% of citizens support our initiative. You should.\"\n    "
- name: Black-and-White_Fallacy
  description: "\n    Presenting two alternative options as the only possibilities,\
    \ when in fact more possibilities exist. As an the extreme case, tell the audience\
    \ exactly what actions to take, eliminating any other possible choices (Dictatorship).\n\
    \    Example 1: \"You must be a Republican or Democrat. You are not a Democrat.\
    \ Therefore, you must be a Republican\"\n    Example 2: \"I thought you were a\
    \ good person, but you weren’t at church today.\"\n    Explanation: The assumption\
    \ here is that if one doesn't attend chuch, one must be bad. Of course, good people\
    \ exist who don’t go to church, and good church-going people could have had a\
    \ really good reason not to be in church.\n    Example 3: \"There is no alternative\
    \ to war\"\n    "
- name: Causal_Oversimplification
  description: "\n    Assuming a single cause or reason when there are actually multiple\
    \ causes for an issue.\n    It includes transferring blame to one person or group\
    \ of people without investigating the complexities of the issue\n    Example 1:\
    \ \"President Trump has been in office for a month and gas prices have been skyrocketing.\
    \ The rise in gas prices is because of President Trump.\"\n    Example 2: \"The\
    \ reason New Orleans was hit so hard with the hurricane was because of all the\
    \ immoral people who live there.\"\n    Explanation: This was an actual argument\
    \ seen in the months that followed hurricane Katrina. Ignoring the validity of\
    \ the claims being made, the arguer is blaming a natural disaster on a group of\
    \ people.\n    Example 3: \"If France had not have declared war on Germany then\
    \ world war two would have never happened.\"\n    "
- name: Doubt
  description: ''
- name: Exaggeration,Minimisation
  description: "\n    Either representing something in an excessive manner: making\
    \ things larger, better, worse (e.g., \"the best of the best\", \"quality guaranteed\"\
    ) or making something seem less important or smaller than it really is (e.g.,\
    \ saying that an insult was just a joke).\n    Example 1: \"Democrats bolted as\
    \ soon as Trump’s speech ended in an apparent effort to signal they can’t even\
    \ stomach being in the same room as the president \"\n    Example 2: \"We’re going\
    \ to have unbelievable intelligence\"\n    Example 3: \"I was not fighting with\
    \ her; we were just playing.\"\n    "
- name: Flag-Waving
  description: "\n    Playing on strong national feeling (or to any group; e.g., race,\
    \ gender, political preference) to justify or promote an action or idea\n    Example\
    \ 1: \"Patriotism mean no questions\" (this is also a slogan)\n    Example 2:\
    \ \"Entering this war will make us have a better future in our country.\"\n  \
    \  "
- name: Loaded_Language
  description: "\n    Using specific words and phrases with strong emotional implications\
    \ (either positive or negative) to influence an audience.\n    Example 1: [...]\
    \ a lone lawmaker’s childish shouting.\n    Example 2: How stupid and petty things\
    \ have become in Washington\n    "
- name: Name_Calling,Labeling
  description: "\n    Labeling the object of the propaganda campaign as either something\
    \ the target audience fears, hates, finds undesirable or loves, praises.\n   \
    \ Example 1: \"Republican congressweasels\", \"Bush the Lesser\" (note that lesser\
    \ does not refer to \"the second\", but it is pejorative)\n    "
- name: Obfuscation,Intentional_Vagueness,Confusion
  description: "\n    Using words which are deliberately not clear so that the audience\
    \ may have its own interpretations.\n    For example when an unclear phrase with\
    \ multiple definitions is used within the argument and, therefore, it does not\
    \ support the conclusion.\n    Example 1: \"It is a good idea to listen to victims\
    \ of theft. Therefore if the victims say to have the thief shot, then you should\
    \ do that.\"\n    Explanation: the definition for \"listen to\" is equivocated\
    \ here. In the first case it means listen to their personal account of the experience\
    \ of being a victim of theft. Empathize with them. In the second case \"listen\
    \ to\" means carry out a punishment of their choice.\n    "
- name: Red_Herring
  description: "\n    Introducing irrelevant material to the issue being discussed,\
    \ so that everyone's attention is diverted away from the points made.\n    Example\
    \ 1: In politics, defending one’s own policies regarding public safety - “I have\
    \ worked hard to help eliminate criminal activity. What we need is economic growth\
    \ that can only come from the hands of leadership.”\n    Example 2: \"You may\
    \ claim that the death penalty is an ineffective deterrent against crime -- but\
    \ what about the victims of crime? How do you think surviving family members feel\
    \ when they see the man who murdered their son kept in prison at their expense?\
    \ Is it right that they should pay for their son's murderer to be fed and housed?\"\
    \n    "
- name: Reductio_ad_hitlerum
  description: "\n    Persuading an audience to disapprove an action or idea by suggesting\
    \ that the idea is popular with groups hated in contempt by the target audience.\
    \ It can refer to any person or concept with a negative connotation.\n    Example\
    \ 1: \"Do you know who else was doing that ? Hitler!\"\n    Example 2: \"Only\
    \ one kind of person can think in that way: a communist.\"\n    "
- name: Repetition
  description: "\n    Repeating the same message over and over again so that the audience\
    \ will eventually accept it.\n    "
- name: Slogans
  description: "\n    A brief and striking phrase that may include labeling and stereotyping.\
    \ Slogans tend to act as emotional appeals.\n    Example 1: \"The more women at\
    \ war . . . the sooner we win.\"\n    Example 2: \"Make America great again!\"\
    \n    "
- name: Straw_Men
  description: '

    When an opponent''s proposition is substituted with a similar one which is then
    refuted in place of the original proposition.


    Example 1: Zebedee: What is your view on the Christian God?

    Mike: I don’t believe in any gods, including the Christian one.

    Zebedee: So you think that we are here by accident, and all this design in nature
    is pure chance, and the universe just created itself?

    Mike: You got all that from me stating that I just don’t believe in any gods?


    Explanation: Mike made one claim: that he does not believe in any gods. From that,
    we can deduce a few things, like he is not a theist, he is not a practicing Christian,
    Catholic, Jew, or a member of any other religion that requires the belief in a
    god, but we cannot deduce that he believes we are all here by accident, nature
    is chance, and the universe created itself.

    '
- name: Thought-terminating_Cliches
  description: '

    Words or phrases that discourage critical thought and meaningful discussion about
    a given topic. They are typically short, generic sentences that offer seemingly
    simple answers to complex questions or that distract attention away from other
    lines of thought.



    Example 1: "It is what it is"; "It''s just common sense"; "You gotta do what you
    gotta do"; "Nothing is permanent except change"; "Better late than never"; "Mind
    your own business"; "Nobody''s perfect"; "It doesn''t matter"; "You can''t change
    human nature."

    '
- name: Whataboutism
  description: '

    A technique that attempts to discredit an opponent''s position by charging them
    with hypocrisy without directly disproving their argument.



    Example 1: "A nation deflects criticism of its recent human rights violations
    by pointing to the history of slavery in the United States."


    Example 2: "Qatar spending profusely on Neymar, not fighting terrorism"

    '
campaign_orig_id: ptc
